### ISSUE TITLE
dae work with adguardhome

### ISSUE THREAD

**Issue by BOBINIUNIU** [v2rayA/dae#31]
I am using adguardhome as upstream DNS but it is not working with dae, the domain traffic split not work. Could you please give me a sample config file. Many thanks!

Node is naiveproxy socks5
adguardhome：china website 223.5.5.5 upd dns，other site Google DoH dns 

My current configuration file is below

global {
    tproxy_port: 12345
    log_level: info
    #tcp_check_url: 'http://keep-alv.google.com/generate_204'
    #udp_check_dns: 'dns.google:53'
    #check_interval: 30s
    #check_tolerance: 50ms
    lan_interface: enp1s0
    # wan_interface: enp1s0
    allow_insecure: false
    dial_mode: domain
}

node {
    fast_node: 'socks5://127.0.0.1:10000'
    cloud_node: 'socks5://127.0.0.1:10001'
}

dns {
    upstream {
        adguardhomedns: 'tcp+udp://127.0.0.1:53'
    }
    #routing {
        #request {
        #fallback: asis
        #}
        #response {
            #upstream(localdns) -> accept
          #  !qname(geosite:cn) && ip(geoip:private) -> googledns
          #fallback: accept
        #}
    #}
}

# Node group (outbound).
group {
   fast_group {
        policy: fixed(0)
    }

   cloud_group {
        policy: fixed(1)
    }

}

routing {
    ### Preset rules.
    pname(AdGuardHome) -> must_direct
    # pname(NetworkManager, systemd-resolved) -> direct
    dip(224.0.0.0/3, 'ff00::/8') -> direct
    dip(geoip:private) -> direct

    ### Write your rules below.
    dip(1.0.0.1) -> fast_group
    dip(1.1.1.1) -> fast_group
    domain(apple.com) -> direct
    domain(apple.news) -> direct
    dip(geoip:cn) -> direct
    domain(geosite:cn) -> direct
    fallback: fast_group
}

**Comment by BOBINIUNIU** [comment]
global {
    # tproxy port to listen on. It is NOT a HTTP/SOCKS port, and is just used by eBPF program.
    # In normal case, you do not need to use it.
    tproxy_port: 12345

    # Log level: error, warn, info, debug, trace.
    log_level: info

    # Node connectivity check.
    # Host of URL should have both IPv4 and IPv6 if you have double stack in local.
    # Considering traffic consumption, it is recommended to choose a site with anycast IP and less response.
    #tcp_check_url: 'http://keep-alv.google.com/generate_204'

    # This DNS will be used to check UDP connectivity of nodes. And if dns_upstream below contains tcp, it also be used to check
    # TCP DNS connectivity of nodes.
    # This DNS should have both IPv4 and IPv6 if you have double stack in local.
    #udp_check_dns: 'dns.google:53'

    #check_interval: 30s

    # Group will switch node only when new_latency <= old_latency - tolerance.
    #check_tolerance: 50ms

    # The LAN interface to bind. Use it if you only want to proxy LAN instead of localhost.
    # Multiple interfaces split by ",".
    lan_interface: enp1s0

    # The WAN interface to bind. Use it if you want to proxy localhost.
    # Multiple interfaces split by ",".
    # wan_interface: enp1s0

    # Allow insecure TLS certificates. It is not recommended to turn it on unless you have to.
    allow_insecure: false

    # Optional values of dial_mode are:
    # 1. "ip". Dial proxy using the IP from DNS directly. This allows your ipv4, ipv6 to choose the optimal path
    #       respectively, and makes the IP version requested by the application meet expectations. For example, if you
    #       use curl -4 ip.sb, you will request IPv4 via proxy and get a IPv4 echo. And curl -6 ip.sb will request IPv6.
    #       This may solve some wierd full-cone problem if your are be your node support that.
    # 2. "domain". Dial proxy using the domain from sniffing. This will relieve DNS pollution problem to a great extent
    #       if have impure DNS environment. Generally, this mode brings faster proxy response time because proxy will
    #       re-resolve the domain in remote, thus get better IP result to connect. This policy does not impact routing.
    #       That is to say, domain rewrite will be after traffic split of routing and dae will not re-route it.
    # 3. "domain+". Based on domain mode but do not check the authenticity of sniffing result. It is useful for users
    #       whose DNS requests do not go through dae but want faster proxy response time. Notice that, if DNS requests
    #       do not go through dae, dae cannot split traffic by domain.
    dial_mode: domain

}

# Subscriptions defined here will be resolved as nodes and merged as a part of the global node pool.
# Support to give the subscription a tag, and filter nodes from a given subscription in the group section.
#subscription {
    # Add your subscription links here.
    #my_sub: 'https://www.example.com/subscription/link'
    #another_sub: 'https://example.com/another_sub'
    #'https://example.com/no_tag_link'
#}

# Nodes defined here will be merged as a part of the global node pool.
node {
    # Add your node links here.
    # Support socks5, http, https, ss, ssr, vmess, vless, trojan, trojan-go
    fast_node: 'socks5://127.0.0.1:10000'
    cloud_node: 'socks5://127.0.0.1:10001'

}

# See more at https://github.com/v2rayA/dae/blob/main/docs/dns.md.
dns {
    upstream {
        # Value can be scheme://host:port, where the scheme can be tcp/udp/tcp+udp.
        # If host is a domain and has both IPv4 and IPv6 record, dae will automatically choose
        # IPv4 or IPv6 to use according to group policy (such as min latency policy).
        # Please make sure DNS traffic will go through and be forwarded by dae, which is REQUIRED for domain routing.
        # If dial_mode is "ip", the upstream DNS answer SHOULD NOT be polluted, so domestic public DNS is not recommended.

        #alidns: 'udp://223.5.5.5:53'
        #googledns: 'tcp+udp://8.8.8.8:53'
        adguardhomedns: 'tcp+udp://127.0.0.1:53'
    }
    #routing {
        #request {
        #fallback: asis
        #}
        #response {
            #upstream(localdns) -> accept
          #  !qname(geosite:cn) && ip(geoip:private) -> googledns
          #fallback: accept
        #}
    #}
}

# Node group (outbound).
group {
   fast_group {
        # No filter. Use all nodes.

        # Randomly select a node from the group for every connection.
        #policy: random

        # Select the first node from the group for every connection.
        policy: fixed(0)

        # Select the node with min last latency from the group for every connection.
        #policy: min

        # Select the node with min moving average of latencies from the group for every connection.
        #policy: min_moving_avg
    }

   cloud_group {
        # No filter. Use all nodes.

        # Randomly select a node from the group for every connection.
        #policy: random

        # Select the first node from the group for every connection.
        policy: fixed(1)

        # Select the node with min last latency from the group for every connection.
        #policy: min

        # Select the node with min moving average of latencies from the group for every connection.
        #policy: min_moving_avg
    }


}

# See https://github.com/v2rayA/dae/blob/main/docs/routing.md for full examples.
routing {
    ### Preset rules.

    # If you set upstream (in section "global") to a DNS service in localhost (dnsmasq, adguard, etc.), to avoid loops,
    # let them "must_direct", which makes DNS requests not redirect back to dae again.
    # "pname" means process name.
    pname(AdGuardHome) -> must_direct

    # Network managers in localhost should be direct to avoid false negative network connectivity check when binding to
    # WAN.
    # pname(NetworkManager, systemd-resolved) -> direct

    # Put it in the front to prevent broadcast, multicast and other packets that should be sent to the LAN from being
    # forwarded by the proxy.
    # "dip" means destination IP.
    dip(224.0.0.0/3, 'ff00::/8') -> direct

    # This line allows you to access private addresses directly instead of via your proxy. If you really want to access
    # private addresses in your proxy host network, modify the below line.
    dip(geoip:private) -> direct

    ### Write your rules below.
    dip(1.0.0.1) -> fast_group
    dip(1.1.1.1) -> fast_group
    domain(apple.com) -> direct
    domain(apple.news) -> direct
    dip(geoip:cn) -> direct
    domain(geosite:cn) -> direct
    fallback: fast_group
}

**Comment by mzz2017** [comment]
1. You should use upstream adguardhome as your DNS like this:
```
routing {
  request {
    fallback: adguardhome
  }
}
```

1. You should set DNS server in DHCP setting as the IP of dae.

**Comment by mzz2017** [comment]
The log shows your AdGuardHome is requesting 127.0.0.1. This should not happen.

**Comment by BOBINIUNIU** [comment]
> The log shows your AdGuardHome is requesting 127.0.0.1:53(itself, I guess). This should not happen.

Yes, dae seems to have intercepted the dns request, but local host and the PC that connected to the transparent gateway can't get the IP address.
The same configuration works fine on v2raya
Thank you for your great project.

A new error 
Mar 13 21:26:32 debian dae[499]: level=warning msg="handlePkt: failed to read from: 127.0.0.1:53 (dialer: direct): read udp [::]:54994: i/o timeout"
Mar 13 21:26:32 debian dae[499]: level=warning msg="handlePkt: failed to read from: 127.0.0.1:53 (dialer: direct): read udp [::]:28874: i/o timeout"
Mar 13 21:26:32 debian dae[499]: level=warning msg="handleConn: handleTCP relay error: read tcp 127.0.0.1:17376->127.0.0.1:10000: read: connection reset by peer"

**Comment by BOBINIUNIU** [comment]
> You are right. I'll look into it. Maybe there is something wrong with dae's new code.

Please send me a message if you need test or log information. Thanks again and have a nice day.

**Comment by mzz2017** [comment]
It should be fixed in https://github.com/v2rayA/dae/commit/207c3430eb50589e4508c56164f93798f06ec9c1. Thank you so much for your issue! Please take a test again.

**Comment by mzz2017** [comment]
> PS. the WAN port and the LAN port are both bound to enp1s0, is this the problem?

It doesn't matter. dae supports this.

**Comment by BOBINIUNIU** [comment]
Thank you for fast update. The good news is the local host works! But the PC connected to the transparent gateway still does not work. no error message appear.

**Comment by mzz2017** [comment]
I think you can configure your DHCP to use a public DNS (such as 8.8.8.8 or 223.5.5.5 but whatever it is); the requests will be intercepted by dae and forwarded to adguardhome.

**Comment by BOBINIUNIU** [comment]
> I think you can configure your DHCP to use a public DNS (such as 8.8.8.8 and 223.5.5.5 but whatever it is); the requests will be intercepted by dae and forwarded to adguardhome. Because if you configure it as `adguardhome_ip:53`, the DNS traffic will be sent to adguardhome directly and not forwareded by dae.

Still not work, should I need change resolv.conf in local host? The current settings is 127.0.0.1 (adguardhome)

![IP](https://user-images.githubusercontent.com/21336893/224735075-d10f578c-36fe-4daf-a52a-4f884bd23ae3.png)

**Comment by mzz2017** [comment]
No. It should be OK. I committed a new patch https://github.com/v2rayA/dae/commit/ea568ebce5a51a93f48515553d4a589e1033e00a. Hope it can resolve it.

**Comment by BOBINIUNIU** [comment]
Sorry, I have recompiled the latest version but no luck. No matter if I set DNS to adguardhome ip or public dns it doesn't work

Can you share your full configuration file?

the error message appears when I set the client DNS to 8.8.8.8
Mar 13 23:09:51 debian bash[461]: [0313/230951.860578:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -100
Mar 13 23:09:51 debian dae[482]: level=info msg="localhost:40588 <-> the server ip:443" dialMode=domain dialer="fast_node" domain=my.server.top mac="7c:2b:e1:13:18:e6" network=tcp4 outbound="fast_group" pid=461 pname=naive policy=fixed
Mar 13 23:09:51 debian dae[482]: level=warning msg="handleConn: handleTCP relay error: read tcp 127.0.0.1:30526->127.0.0.1:10000: read: connection reset by peer"
Mar 13 23:09:51 debian bash[461]: [0313/230951.876978:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -100

**Comment by mzz2017** [comment]
OK.. But what is the naive process? I notice that the naive proxy is in the log. Are logs generated quickly now?

**Comment by BOBINIUNIU** [comment]
I don't think it's a problem with naiveproxy. On the local host, the proxy works fine. But the client still can't get the IP address.

root@debian:~# wget qq.com
--2023-03-13 23:37:31--  http://qq.com/
Resolving qq.com (qq.com)... 123.151.137.18, 61.129.7.47, 183.3.226.35
Connecting to qq.com (qq.com)|123.151.137.18|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.qq.com/ [following]
--2023-03-13 23:37:31--  https://www.qq.com/
Resolving www.qq.com (www.qq.com)... 121.14.77.221, 121.14.77.201
Connecting to www.qq.com (www.qq.com)|121.14.77.221|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.10’


index.html.10           [ <=>                ]  26.67K  --.-KB/s    in 0.02s


2023-03-13 23:37:31 (1.30 MB/s) - ‘index.html.10’ saved [27307]


root@debian:~# wget google.com
--2023-03-13 23:37:37--  http://google.com/
Resolving google.com (google.com)... 142.250.176.14
Connecting to google.com (google.com)|142.250.176.14|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2023-03-13 23:37:37--  http://www.google.com/
Resolving www.google.com (www.google.com)... 142.250.188.228
Connecting to www.google.com (www.google.com)|142.250.188.228|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.11’


index.html.11           [ <=>                ]  15.73K  --.-KB/s    in 0.02s


2023-03-13 23:37:38 (772 KB/s) - ‘index.html.11’ saved [16103]

**Comment by mzz2017** [comment]
OK Do you have a linux machine? You can set log_level to trace in the dae configuration file, then:
1. Use `dig` to test whether the dns is fine.
2. Use `curl 1.1.1.1` to test whether the request will be successful without dns.
I'm not sure whether you can do this on Windows with similar tools.

**Comment by mzz2017** [comment]
Thanks for your help. Good night.

**Comment by BOBINIUNIU** [comment]
dig and curl output
root@test:~# dig qq.com

; <<>> DiG 9.16.37-Debian <<>> qq.com
;; global options: +cmd
;; connection timed out; no servers could be reached

root@test:~# dig google.com

; <<>> DiG 9.16.37-Debian <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached

root@test:~# curl -O 11.html qq.com
curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application

DAE Log
Mar 14 09:50:22 debian dae[463]: level=trace msg="Request to DNS upstream" question=[{qq.com. TypeA ClassINET}] upstream="tcp+udp://127.0.0.1:53"
Mar 14 09:50:22 debian dae[463]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp tcp] upstream="tcp+udp://127.0.0.1:53"
Mar 14 09:50:22 debian dae[463]: level=trace msg="Update DNS record cache" addition=".(TypeOPT): dnsmessage.OPTResource{Options: []dnsmessage.Option{}}" ans="qq.com.(TypeA): 123.151.137.18; qq.com.(TypeA): 61.129.7.47; qq.com.(TypeA): 183.3.226.35" auth= qname=qq.com. rcode=RCodeSuccess
Mar 14 09:50:22 debian dae[463]: level=trace msg=Accept question=[{qq.com. TypeA ClassINET}] upstream="tcp+udp://127.0.0.1:53"
Mar 14 09:50:22 debian dae[463]: level=info msg="192.168.1.12:43311 <-> 127.0.0.1:53" dialer=direct mac="26:0e:1b:34:f6:6d" network="udp4(DNS)" outbound=direct pid=0 pname= policy=fixed qname=qq.com. qtype=TypeA
Mar 14 09:50:27 debian dae[463]: level=trace msg="UDP(DNS) 192.168.1.12:43311 <-> Cache: qq.com. TypeA"
Mar 14 09:50:32 debian dae[463]: level=trace msg="UDP(DNS) 192.168.1.12:43311 <-> Cache: qq.com. TypeA"
Mar 14 09:51:27 debian dae[463]: level=trace msg="Request to DNS upstream" question=[{google.com. TypeA ClassINET}] upstream="tcp+udp://127.0.0.1:53"
Mar 14 09:51:27 debian dae[463]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp tcp] upstream="tcp+udp://127.0.0.1:53"
Mar 14 09:51:27 debian dae[463]: level=info msg="localhost:46598 <-> 1.0.0.1:443" dialMode=ip dialer="fast_node" domain= mac="7c:2b:e1:13:18:e6" network=tcp4 outbound="fast_group" pid=445 pname=AdGuardHome policy=fixed
Mar 14 09:51:28 debian dae[463]: level=trace msg="Update DNS record cache" addition=".(TypeOPT): dnsmessage.OPTResource{Options: []dnsmessage.Option{}}" ans="google.com.(TypeA): 172.217.14.78" auth= qname=google.com. rcode=RCodeSuccess
Mar 14 09:51:28 debian dae[463]: level=trace msg=Accept question=[{google.com. TypeA ClassINET}] upstream="tcp+udp://127.0.0.1:53"
Mar 14 09:51:28 debian dae[463]: level=info msg="192.168.1.12:44100 <-> 127.0.0.1:53" dialer=direct mac="26:0e:1b:34:f6:6d" network="udp4(DNS)" outbound=direct pid=0 pname= policy=fixed qname=google.com. qtype=TypeA
Mar 14 09:51:32 debian dae[463]: level=trace msg="UDP(DNS) 192.168.1.12:44100 <-> Cache: google.com. TypeA"
Mar 14 09:51:37 debian dae[463]: level=trace msg="UDP(DNS) 192.168.1.12:44100 <-> Cache: google.com. TypeA"

**Comment by mzz2017** [comment]
what about curl 1.1.1.1

**Comment by mzz2017** [comment]
I think it may be a NIC problem. Try to listen AdGuardHome on a non-53 port.

Don't fotget to modify corresponding upstream settings in dae config.

**Comment by BOBINIUNIU** [comment]
> what about curl 1.1.1.1

root@test:~# curl 1.1.1.1
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

**Comment by BOBINIUNIU** [comment]
> I think it may be a NIC problem. Try to listen AdGuardHome on a non-53 port.
> 
> Don't fotget to modify corresponding upstream settings in dae config.

Modified the adguardhome port but still the same result

dns {
     upstream {
      adguardhomedns: 'tcp+udp://127.0.0.1:54'
             }
routing {
    request {
      fallback: adguardhomedns
    }
  }
}
routing {
    pname(AdGuardHome) && l4proto(udp) && dport(54) -> must_direct
    pname(NetworkManager, systemd-resolved) -> direct

**Comment by mzz2017** [comment]
So weird. I have the same configuration but cannot reproduce.

**Comment by mzz2017** [comment]
What if you do not use adguard home?

**Comment by mzz2017** [comment]
Will adguardhome work (test it on port 53) when dae is stopped?

**Comment by BOBINIUNIU** [comment]
> What if you do not use adguardhome? Will it perform fine?

I have changed dns settings in dae and client to 1.1.1.1, same result. If remove the dns section in ade, it works.

dns {
     upstream {
      adguardhomedns: 'udp://1.1.1.1:53'
             }
routing {
    request {
      fallback: adguardhomedns
    }
  }
}


nameserver 1.1.1.1

**Comment by BOBINIUNIU** [comment]
> Will adguardhome work (test it on port 53) when dae is stopped?

Yes, adguardhome works fine. The problem only occurs after added dns section to dae

**Comment by mzz2017** [comment]
Ok... Good change... So if you change upstream from udp://127.0.0.1:53 to udp://223.5.5.5:53, will it remain failure?

**Comment by BOBINIUNIU** [comment]
> Ok... Good change... So if you change fallback:adgaurdhome to fallback:asis, will it remain failure?

changed dns to 1.1.1.1 and fallback to asis, I got these errors

Mar 14 11:50:23 debian dae[481]: level=trace msg="Request to DNS upstream" question=[{qq.com. TypeA ClassINET}] upstream=asis
Mar 14 11:50:23 debian dae[481]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp] upstream="udp://1.1.1.1:53"
Mar 14 11:50:23 debian dae[481]: level=trace msg="Request to DNS upstream" question=[{qq.com. TypeAAAA ClassINET}] upstream=asis
Mar 14 11:50:23 debian dae[481]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp] upstream="udp://1.1.1.1:53"
Mar 14 11:50:23 debian dae[481]: level=warning msg="handlePkt: failed to dial '1.1.1.1:53': proxy: SOCKS5 proxy at 127.0.0.1:10000 failed to connect: command not supported by socks5 server: UDPAssociate"
Mar 14 11:50:23 debian dae[481]: level=warning msg="handlePkt: failed to dial '1.1.1.1:53': proxy: SOCKS5 proxy at 127.0.0.1:10000 failed to connect: command not supported by socks5 server: UDPAssociate"
Mar 14 11:50:28 debian dae[481]: level=trace msg="Request to DNS upstream" question=[{qq.com. TypeA ClassINET}] upstream=asis
Mar 14 11:50:28 debian dae[481]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp] upstream="udp://1.1.1.1:53"
Mar 14 11:50:28 debian dae[481]: level=trace msg="Request to DNS upstream" question=[{qq.com. TypeAAAA ClassINET}] upstream=asis
Mar 14 11:50:28 debian dae[481]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp] upstream="udp://1.1.1.1:53"
Mar 14 11:50:28 debian dae[481]: level=warning msg="handlePkt: failed to dial '1.1.1.1:53': proxy: SOCKS5 proxy at 127.0.0.1:10000 failed to connect: command not supported by socks5 server: UDPAssociate"
Mar 14 11:50:28 debian dae[481]: level=warning msg="handlePkt: failed to dial '1.1.1.1:53': proxy: SOCKS5 proxy at 127.0.0.1:10000 failed to connect: command not supported by socks5 server: UDPAssociate"

**Comment by mzz2017** [comment]
Please change your dns to 223.5.5.5 and try again.

**Comment by BOBINIUNIU** [comment]
> Please change your dns to 223.5.5.5 and try again.

Changed dns on both client and dae but no luck.

Mar 14 11:58:26 debian dae[483]: level=trace msg="Request to DNS upstream" question=[{qq.com. TypeA ClassINET}] upstream=asis
Mar 14 11:58:26 debian dae[483]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp] upstream="udp://223.5.5.5:53"
Mar 14 11:58:26 debian dae[483]: level=trace msg="Request to DNS upstream" question=[{qq.com. TypeAAAA ClassINET}] upstream=asis
Mar 14 11:58:26 debian dae[483]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp] upstream="udp://223.5.5.5:53"
Mar 14 11:58:26 debian dae[483]: level=trace msg="Update DNS record cache" addition=".(TypeOPT): dnsmessage.OPTResource{Options: []dnsmessage.Option{}}" ans="qq.com.(TypeA): 61.129.7.47; qq.com.(TypeA): 183.3.226.35; qq.com.(TypeA): 123.151.137.18" auth= qname=qq.com. rcode=RCodeSuccess
Mar 14 11:58:26 debian dae[483]: level=trace msg=Accept question=[{qq.com. TypeA ClassINET}] upstream=asis
Mar 14 11:58:26 debian dae[483]: level=info msg="192.168.1.12:58889 <-> 223.5.5.5:53" dialer=direct mac="26:0e:1b:34:f6:6d" network="udp4(DNS)" outbound=direct pid=0 pname= policy=fixed qname=qq.com. qtype=TypeA
Mar 14 11:58:26 debian dae[483]: level=trace msg=Accept question=[{qq.com. TypeAAAA ClassINET}] upstream=asis
Mar 14 11:58:26 debian dae[483]: level=info msg="192.168.1.12:58889 <-> 223.5.5.5:53" dialer=direct mac="26:0e:1b:34:f6:6d" network="udp4(DNS)" outbound=direct pid=0 pname= policy=fixed qname=qq.com. qtype=TypeAAAA
Mar 14 11:58:31 debian dae[483]: level=trace msg="UDP(DNS) 192.168.1.12:58889 <-> Cache: qq.com. TypeA"
Mar 14 11:58:31 debian dae[483]: level=trace msg="Request to DNS upstream" question=[{qq.com. TypeAAAA ClassINET}] upstream=asis
Mar 14 11:58:31 debian dae[483]: level=trace msg="Choose DNS path" ipversions=[4] l4protos=[udp] upstream="udp://223.5.5.5:53"
Mar 14 11:58:32 debian dae[483]: level=trace msg=Accept question=[{qq.com. TypeAAAA ClassINET}] upstream=asis
Mar 14 11:58:32 debian dae[483]: level=info msg="192.168.1.12:58889 <-> 223.5.5.5:53" dialer=direct mac="26:0e:1b:34:f6:6d" network="udp4(DNS)" outbound=direct pid=0 pname= policy=fixed qname=qq.com. qtype=TypeAAAA

here is the full config file
[config.dae.txt](https://github.com/v2rayA/dae/files/10964003/config.dae.txt)

**Comment by mzz2017** [comment]
There is a weird point. If your proxy does not support UDP, why after removing DNS section it can forward traffic to 1.1.1.1:53 successfully?

**Comment by mzz2017** [comment]
I see. You mean that DNS server use adguardhome.

**Comment by mzz2017** [comment]
I think dae should act like a normal dns server when port 53 is not in use. Can you reach me on telegram? @mzz2017

**Comment by BOBINIUNIU** [comment]
> I think dae should act like a normal dns server when port 53 is not in use. Can you reach me on telegram? @mzz2017

Sorry, my telegram account is currently unavailable

If the dns setting is added to dae, does that mean dae will listening on port 53? Maybe I should stop the adguradhome service and try again

**Comment by mzz2017** [comment]
Dae will not actually listen on port 53. It uses a magic method to simulate. Use `sudo netstat -ulpen` or `sudo lsof -i:53` to make sure 53 is not be listened on.

**Comment by BOBINIUNIU** [comment]
I have disabled Adguardhome then changed dae dns and client dns to 223.5.5.5, it works now!

**Comment by mzz2017** [comment]
Generally, it works fine regardless of whether other programs listen to 53. However, it will fail when you have some other program listen on port 53 and your NIC does not support to disable checksum verification in the production environment.

**Comment by BOBINIUNIU** [comment]
> 

Disable NIC checksum verification, do you mean this command？
ethtool --offload <NETWORK INTERFACE> tx off

**Comment by mzz2017** [comment]
> Disable NIC checksum verification, do you mean this command？ ethtool --offload tx off

No, it has nothing with offload. Do not disable it.

**Comment by BOBINIUNIU** [comment]
Maybe I should give up using adguardhome if dae also supports the dns caching feature

**Comment by mzz2017** [comment]
> Maybe I should give up using adguardhome if dae also supports the dns caching feature

Yes. You can do this. Now dae only supports tcp/udp. DoH, DoT, DoQ is ongoing. And if you still want to use adguardhome, I think trying changing the listening port is a good method.

Anyway, thanks for help with debugging.

**Comment by BOBINIUNIU** [comment]
Can I using Doh in dae like this  1111dns: 'https://1.0.0.1/dns-query:443'

**Comment by mzz2017** [comment]
Not yet. dae does not support DoH yet.

**Comment by mzz2017** [comment]
Of course, this feature is important, and I think it should be supported in the first half of this year.

**Comment by BOBINIUNIU** [comment]
> Of course, this feature is important, and I think it should be supported in the first half of this year.

I will continue testing in the evening. Thank you very much for your patience!
dae is indeed faster than v2raya, hope it support Doh soon. good job!

**Comment by mzz2017** [comment]
Thank you! Have a good day!

**Comment by mzz2017** [comment]
I'll close this issue as completed. If you have other problems. Please open another issue.

**Comment by imbillow** [comment]
I don't think this problem has been solved

**Comment by GhostStar** [comment]
I'm having the same problem, I'm using adguardhome as the upstream for dae, hoping to be able to see the original client ip for auditing, but with the following configuration although adg can see the original client ip, the dae functionality is disabled

pname(NetworkManager, systemd-resolved, dnsmasq, tailscaled) -> direct
pname(AdGuardHome) -> must_direct
dip(geoip:private) -> must_direct
